apps/accounts/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
    path('cadastrar/', views.register, name='register'),
    path('editar/', views.edit, name='edit'),
    path('editar_senha/', views.edit_password, name='edit_password'),
    
    path('cadastrar/', views.register, name='resume'),
    path('series/', views.DashboardSeries, name='DashboardSeries'),
    path('animes/', views.DashboardAnimes, name='DashboardAnimes'),
    path('mangas/', views.DashboardMangas, name='DashboardMangas'),
    path('filmes/', views.DashboardMovies, name='DashboardMovies'),
    path('livros/', views.DashboardBooks, name='DashboardBooks'),
    
    path('favoritos/', views.DashboardFavorites, name='DashboardFavorites'),
    path('removerfavorito/<int:id>/<str:type>/', views.RemoverFavorito, name='RemoverFavorito'),

    path('gerenciar/', views.DashboardManager, name='DashboardManager'),
    path('add_serie/', views.DashboardAddSerie, name='DashboardAddSerie'),
    path('add_serie_completa/', views.DashboardAddSerieCompleta, name='DashboardAddSerieCompleta'),
    path('add_anime/', views.DashboardAddAnime, name='DashboardAddAnime'),
    path('add_anime_completo/', views.DashboardAddAnimeCompleto, name='DashboardAddAnimeCompleto'),
    path('add_manga/', views.DashboardAddManga, name='DashboardAddManga'),
    path('add_manga_completo/', views.DashboardAddMangaCompleto, name='DashboardAddMangaCompleto'),
    path('add_filme/', views.DashboardAddMovie, name='DashboardAddMovie'),
    path('add_livro/', views.DashboardAddBook, name='DashboardAddBook'),
    path('remove/', views.DashboardRemove, name='DashboardRemove'),
]

apps/animes/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListAnime, name='ListAnime'),
    path('<int:id>/', views.ListSeasonAnime, name='ListSeasonAnime'),
    path('<int:anime_id>/<int:season_id>/', views.ListEpisodeAnime, name='ListEpisodeAnime'),
    path('inserirepisodeanime/<int:episode_id>/', views.InserirAssistidoEpisodeAnime, name='InserirAssistidoEpisodeAnime'),
    path('inserirseasonanime/<int:season_id>/<int:anime_id>/', views.InserirAssistidoSeasonAnime, name='InserirAssistidoSeasonAnime'),
    path('inserirfavoritoanime/<int:anime_id>/', views.InserirAnimeFavorito, name='InserirAnimeFavorito'),
    path('adicionarNovoEP/<int:season_id>/<int:anime_id>/', views.AdicionarNovoEP, name='AdicionarNovoEP')
]

apps/mangas/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListManga, name='ListManga'),
    path('<int:id>/', views.ListVolumeManga, name='ListVolumeManga'),
    path('<int:manga_id>/<int:volume_id>/', views.ListChapterManga, name='ListChapterManga'),
    path('inserirchaptermanga/<int:chapter_id>/', views.InserirLidoChapterManga, name='InserirLidoChapterManga'),
    path('inserirvolumemanga/<int:volume_id>/<int:manga_id>/', views.InserirLidoVolumeManga, name='InserirLidoVolumeManga'),
]

apps/series/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListSerie, name='ListSerie'),
    path('<int:id>/', views.ListSeasonSerie, name='ListSeasonSerie'),
    path('<int:serie_id>/<int:season_id>/', views.ListEpisodeSerie, name='ListEpisodeSerie'),
    path('inserirepisodeanime/<int:episodeserie_id>/', views.InserirAssistidoEpisodeSerie, name='InserirAssistidoEpisodeSerie'),
    path('inserirseasonserie/<int:season_id>/<int:serie_id>/', views.InserirAssistidoSeasonSerie, name='InserirAssistidoSeasonSerie'),
    path('inserirfavoritaserie/<int:serie_id>/', views.InserirSerieFavorita, name='InserirSerieFavorita'),
    path('adicionarNovoEP/<int:season_id>/<int:serie_id>/', views.AdicionarNovoEP, name='AdicionarNovoEP')
]

keepcontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views

urlpatterns = [ 
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('animes/', include(('apps.animes.urls', 'animes'), namespace='animes')),
    path('filmes/', include(('apps.movies.urls', 'movies'), namespace='movies')),    
    path('series/', include(('apps.series.urls', 'series'), namespace='series')),
    path('livros/', include(('apps.books.urls', 'books'), namespace='books')),    
    path('mangas/', include(('apps.mangas.urls', 'mangas'), namespace='mangas')), 
    path('conta/', include(('apps.accounts.urls','accounts'), namespace='accounts')) ,
    path('admin/', admin.site.urls)
]

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.conf import settings
from .forms import *
from apps.movies.models import Movie
from apps.series.models import EpisodeSerie, Serie, SeasonSerie
from apps.animes.models import EpisodeAnime, Anime, SeasonAnime
from apps.mangas.models import ChapterManga, Manga, VolumeManga
from apps.books.models import Book
from .models import UserEpisodeAnime, UserEpisodeSerie, UserMovie, UserChapterManga, UserBook, FavoriteManga, FavoriteAnime, FavoriteBook, FavoriteMovie, FavoriteSerie, FavoritesView
from itertools import chain
from django.contrib.auth.decorators import user_passes_test
from apps.series.views import *
from django.contrib import messages
from django.db import IntegrityError
# Create your views here.
@login_required
def dashboard(request):
    
    epanimes = (
        EpisodeAnime.objects
        .filter(userepisodeanime__user_id=request.user.id)
        .order_by('-userepisodeanime__date_watched')
        .values('season__anime__id','pt_title', 'number', 'userepisodeanime__date_watched', 'season__number', 'season__anime__or_title')
    )
    movies = (
        Movie.objects
        .filter(usermovie__user_id=request.user.id)
        .order_by('-usermovie__date_watched')
        .values('pt_title','year', 'usermovie__date_watched')
    )
    epseries = (
        EpisodeSerie.objects
        .filter(userepisodeserie__user_id=request.user.id)
        .order_by('-userepisodeserie__date_watched')
        .values('season__serie__id','pt_title', 'number', 'userepisodeserie__date_watched', 'season__number', 'season__serie__or_title')
    )
    books = (
        Book.objects
        .filter(userbook__user_id=request.user.id)
        .order_by('-userbook__date_watched')
        .values('pt_title', 'year', 'userbook__date_watched')
    )
    capmangas = (
        ChapterManga.objects
        .filter(userchaptermanga__user_id=request.user.id)
        .order_by('-userchaptermanga__date_watched')
        .values('volume__manga__id','pt_title', 'number', 'userchaptermanga__date_watched', 'volume__number', 'volume__manga__or_title')
    )
    #preciso ordernar pela data assistida
    for x in books:
        x['date_watched'] = x.pop('userbook__date_watched')
        x['type'] = 'Livro'
    for x in epanimes:
        x['date_watched'] = x.pop('userepisodeanime__date_watched')
        x['type'] = 'Anime'
    for x in movies:
        x['date_watched'] = x.pop('usermovie__date_watched')
        x['type'] = 'Filme'
    for x in epseries:
        x['date_watched'] = x.pop('userepisodeserie__date_watched')
        x['type'] = 'Série'
    for x in capmangas:
        x['date_watched'] = x.pop('userchaptermanga__date_watched')
        x['type'] = 'Mangá'
    
    todos = list(chain(epanimes, movies, epseries, books, capmangas))

    # Define uma função para obter a data assistida de um dicionário
    def get_date_watched(item):
        return item.get('date_watched', None)  # Retorna None se a chave não existir

    sorted_todos = sorted(todos, key=get_date_watched, reverse=True)[:25]
    
    context = {
        'all': sorted_todos
    }
    template_name = 'dashboard.html'
    return render(request, template_name, context)

def register(request):
    template_name = 'register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=user.username, password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'edit.html'
    context = {}
    if request.method == 'POST': #Se o método for POST
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
            #return redirect ('app_accounts:dashboard')
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request,template_name, context)

@login_required
def edit_password(request):
    template_name = 'edit_password.html'
    context = {}
    if request.method == 'POST': #Se o método for POST
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
            
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required
def DashboardSeries(request):
    context = {}
    qtd_assistidos = UserEpisodeSerie.objects.filter(user=request.user).count()
    epseries = (
        EpisodeSerie.objects
        .filter(userepisodeserie__user_id=request.user.id)
        .order_by('-userepisodeserie__date_watched')
        .values('pt_title', 'number', 'userepisodeserie__date_watched', 'season__number', 'season__serie__or_title')[:10]
    )
    
    context = {
        'total_assistidos': qtd_assistidos,
        'epseries': epseries,
        'qtd_assistidos': epseries.count
        
    }
    template_name = 'DashboardSeries.html'
    return render(request, template_name, context)

@login_required
def DashboardAnimes(request):
    context = {}
    qtd_assistidos = UserEpisodeAnime.objects.filter(user=request.user).count()
    epanimes = (
        EpisodeAnime.objects
        .filter(userepisodeanime__user_id=request.user.id)
        .order_by('-userepisodeanime__date_watched')
        .values('pt_title', 'number', 'userepisodeanime__date_watched', 'season__number', 'season__anime__or_title')[:10]
    )
    context = {
        'qtd_assistidos': epanimes.count,
        'epanimes': epanimes,
        'qtd_total': qtd_assistidos
    }
    template_name = 'DashboardAnimes.html'
    return render(request, template_name, context)

@login_required
def DashboardMovies(request):
    context = {}
    qtd_assistidos = UserMovie.objects.filter(user=request.user).count()
    movies = (
        Movie.objects
        .filter(usermovie__user_id=request.user.id)
        .order_by('-usermovie__date_watched')
        .values('pt_title', 'usermovie__date_watched')[:10]
    )

    context = {
        'total_assistidos': qtd_assistidos,
        'movies': movies,
        'qtd_assistidos': movies.count
    }
    template_name = 'DashboardMovies.html'
    return render(request, template_name, context)

@login_required
def DashboardMangas(request):
    context = {}
    qtd_lidos = UserChapterManga.objects.filter(user=request.user).count()
    capmangas = (
        ChapterManga.objects
        .filter(userchaptermanga__user_id=request.user.id)
        .order_by('-userchaptermanga__date_watched')
        .values('pt_title', 'number', 'userchaptermanga__date_watched', 'volume__number', 'volume__manga__or_title')[:10]
    )
    context = {
        'total_lidos': qtd_lidos,
        'capmangas': capmangas,
        'qtd_lidos': capmangas.count
    }
    template_name = 'DashboardMangas.html'
    return render(request, template_name, context)

@login_required
def DashboardBooks(request):
    context = {}
    qtd_lidos = UserBook.objects.filter(user=request.user).count()
    books = (
        Book.objects
        .filter(userbook__user_id=request.user.id)
        .order_by('-userbook__date_watched')
        .values('pt_title', 'userbook__date_watched')[:10]
    )

    context = {
        'total_lidos': qtd_lidos,
        'qtd_lidos': books.count,
        'books': books,
        
    }
    template_name = 'DashboardBooks.html'
    return render(request, template_name, context)

@login_required
def DashboardFavorites(request):
    context = {}
      
    todos = FavoritesView.objects.filter(user=request.user.id)
    todos_objetos = []
    for x in todos:
        if x.type == 'Anime':
            b = FavoriteAnime.objects.filter(anime_id = x.conteudo_id).first().anime
            b.percentual = percentual_lido_anime(request=request, anime=b)
            b.type = x.type
            todos_objetos.append(b)
        elif x.type == 'Mangá':
            b = FavoriteManga.objects.filter(manga_id = x.conteudo_id).first().manga
            b.percentual = percentual_lido_manga(request=request, manga=b)
            b.type = x.type
            todos_objetos.append(b)
        elif x.type == 'Série':
            b = FavoriteSerie.objects.filter(serie_id = x.conteudo_id).first().serie
            b.percentual = percentual_lido_serie(request=request, serie=b)
            b.type = x.type
            todos_objetos.append(b)
        elif x.type == 'Livro':
            b = FavoriteBook.objects.filter(book_id = x.conteudo_id).first().book
            b.percentual = 100
            b.type = x.type
            todos_objetos.append(b)
        elif x.type == 'Filme':
            b = FavoriteMovie.objects.filter(movie_id = x.conteudo_id).first().movie
            b.percentual = 100
            b.type = x.type
            todos_objetos.append(b)
   
    context = {
        'qtd_favorites': todos_objetos.count,
        'favorites': todos_objetos,
    }
    
    template_name = 'DashboardFavorites.html'
    return render(request, template_name, context)

@login_required
def percentual_lido_manga(request, manga):
    qtd_chapters = 0
    qtd_chapters_watched = 0
    mangasvolume = VolumeManga.objects.filter(manga_id=manga.id)
    for volume in mangasvolume:
        volumechapters = ChapterManga.objects.filter(volume_id = volume.id)
        volumechapters_watched = UserChapterManga.objects.filter(chapter__volume_id = volume.id, user=request.user)

apps/accounts/templates/DashboardAddAnime.html
{% extends "DashboardManager.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardAddAnime' %}">Adicionar</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Adicionar</div>
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <br>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Adicionar Animes</legend>
                {{ form.non_field_errors }}
                {% for field in form_anime %}
                <div class="pure-control-group">
                    {{field.label_tag}}
                    {{field}}
                    {{field.errors}}
                </div>
                {% endfor %}
                <br>
                <div class="pure-controls">
                    <button type="submit" name="submit_anime" class="pure-button pure-button-primary">Adicionar</button>
                </div>
            </fieldset>
        </form>
        <br>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Adicionar Temporadas</legend>
                {{ form.non_field_errors }}
                {% for field in form_seasonanime %}
                <div class="pure-control-group">
                    {{field.label_tag}}
                    {{field}}
                    {{field.errors}}
                </div>
                {% endfor %}
                <br>
                <div class="pure-controls">
                    <button type="submit" name="submit_season" class="pure-button pure-button-primary">Adicionar</button>
                </div>
            </fieldset>
        </form>
        <br>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Adicionar Episódios</legend>
                {{ form.non_field_errors }}
                {{ form_episodeanime.or_title.label_tag }}
                {{ form_episodeanime.or_title }}
                {{ form_episodeanime.or_title.errors }}
                
                {{ form_episodeanime.pt_title.label_tag }}
                {{ form_episodeanime.pt_title }}
                {{ form_episodeanime.pt_title.errors }}
                
                {{ form_episodeanime.number.label_tag }}
                {{ form_episodeanime.number }}
                {{ form_episodeanime.number.errors }}
                
                {{ form_episodeanime.season.label_tag }}
                {{ form_episodeanime.season }}
                {{ form_episodeanime.season.errors }}
                <br><br>
                <div class="pure-controls">
                    <button type="submit" name="submit_episode" class="pure-button pure-button-primary">Adicionar</button>
                </div>
            </fieldset>
        </form> 
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script type="application/javascript">
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
{% endblock %}

apps/accounts/templates/DashboardAddMangaCompleto.html
{% extends "DashboardManager.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardAddMangaCompleto' %}">Adicionar Completo</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Adicionar</div>
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <br>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Adicionar Mangás</legend>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{field.label_tag}}
                    {{field}}
                    {{field.errors}}
                </div>
                {% endfor %}
                <br>
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Adicionar</button>
                </div>
            </fieldset>
        </form> 
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script type="application/javascript">
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
{% endblock %}

apps/accounts/templates/DashboardAddSerieCompleta.html
{% extends "DashboardManager.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardAddSerieCompleta' %}">Adicionar Completa</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Adicionar</div>
    <div>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <br>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Adicionar Séries</legend>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{field.label_tag}}
                    {{field}}
                    {{field.errors}}
                </div>
                {% endfor %}
                <br>
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Adicionar</button>
                </div>
            </fieldset>
        </form> 
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script type="application/javascript">
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
{% endblock %}

apps/accounts/templates/DashboardFavorites.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardFavorites' %}">Favoritos</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Favoritos</div>
    <table class="table_c">
        <thead>
            <tr>
                <th>#</th>
                <th>Título</th>
                <th>Percentual assistido</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            {% for favorito in favorites %}
            <tr>
                    <td>{{favorito.type}}</td>
                {% if favorito.pt_title%}
                    <td><a class="detalhe" href="{{ favorito.get_absolute_url }}">{{ favorito.pt_title }}</a></td>
                {%else%}
                    <td><a class="detalhe" href="{{ favorito.get_absolute_url }}">{{ favorito.or_title }}</a></td>
                {%endif%}
                    <td>{{ favorito.percentual|floatformat:2 }}%</td>
                    <td><a class="detalhe" href="{% url 'accounts:RemoverFavorito' favorito.id favorito.type %}">Remover</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

apps/accounts/templates/DashboardManager.html
<style>
    .button_gerenciar {
        padding: 7px;
        margin: 5px;
    }
</style>

{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardManager' %}">Gerenciar</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Adicionar</div>
    <div>
        <a href="{% url 'accounts:DashboardAddSerie' %}">Adicionar Série/Temporada/Episódio</a>
        <br>
        <a href="{% url 'accounts:DashboardAddSerieCompleta' %}">Adicionar Série Completa</a>
    </div><br>
    <div>
        <a href="{% url 'accounts:DashboardAddAnime' %}">Adicionar Anime/Temporada/Episódio</a>
        <br>
        <a href="{% url 'accounts:DashboardAddAnimeCompleto' %}">Adicionar Anime Completa</a>
    </div><br>
    <div>
        <a href="{% url 'accounts:DashboardAddManga' %}">Adicionar Mangá/Volume/Capítulo</a>
        <br>
        <a href="{% url 'accounts:DashboardAddMangaCompleto' %}">Adicionar Mangá Completo</a>
    </div><br>
    <div>
        <a href="{% url 'accounts:DashboardAddMovie' %}">Adicionar Filme</a>
    </div><br>
    <div>
        <a href="{% url 'accounts:DashboardAddBook' %}">Adicionar Livro</a>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<script type="application/javascript">
    $(document).ready(function() {
        $('.select2').select2();
    });
</script>
{% endblock %}

apps/accounts/templates/DashboardRemove.html
{% extends "dashboard.html" %}

{% block breadcrumb %}
    {{block.super}}
    <li>|</li>
    <li><a href="{% url 'accounts:DashboardRemove' %}">Adicionar</a></li>
{% endblock %}

{% block dashboard_content %}
<div>
    <div class="pure-menu-li">Remover</div>
    <table class="table_c">
        <thead>
            <tr>
                <th>#</th>
                <th>Título</th>
                <th>Percentual assistido</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

apps/accounts/templates/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block principal %}
<article>
    <div>
        <ul class="breadcrumb">
            {% block breadcrumb %}
            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
            {% endblock %}
        </ul>
    </div>
    <div class="principal-group">
        <div class="left-side-menu">
            <div>
                <ul>
                    <li class="pure-menu-li">Minha Conta</li>
                    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
                </ul>
                <ul>
                    <li class="pure-menu-li">Conteúdos</li>
                    <li><a href="{% url 'accounts:DashboardSeries' %}">Séries</a></li>
                    <li><a href="{% url 'accounts:DashboardAnimes' %}">Animes</a></li>
                    <li><a href="{% url 'accounts:DashboardMangas' %}">Mangás</a></li>
                    <li><a href="{% url 'accounts:DashboardMovies' %}">Filmes</a></li>
                    <li><a href="{% url 'accounts:DashboardBooks' %}">Livros</a></li>
                </ul>
                <ul>
                    <li class="pure-menu-li">Favoritos</li>
                    <li><a href="{% url 'accounts:DashboardFavorites' %}">Favoritos</a></li>
                </ul>
                {% if user.is_staff %}
                <ul>
                    <li class="pure-menu-li">Gerenciar</li>
                    <li><a href="{% url 'accounts:DashboardManager' %}">Gerenciar</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="right-side-body">
            {% block dashboard_content %}
                <div>
                    <p><strong>Nome</strong>: {{ user.name }}</p>
                    <p><strong>Usuário</strong>: {{ user.username }}</p>
                    <p><strong>E-mail</strong>: {{ user.email }}</p>
                </div>
                <div>
                    <h4>Últimos adicionados</h4>
    
                    <table class="table_c">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Título</th>
                                <th>Data</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for x in all %}
                                {%if x.type == 'Filme' %}
                                    <tr>
                                        <td>{{x.type}}</td>
                                        <td>{{x.pt_title}} ({{x.year}})</td>
                                        <td>{{x.date_watched}}</td>
                                    </tr>
                                {%elif x.type == 'Livro' %}
                                    <tr>
                                        <td>{{x.type}}</td>
                                        <td>{{x.pt_title}} ({{x.year}})</td>
                                        <td>{{x.date_watched}}</td>
                                    </tr>
                                {%elif x.type == 'Série' %}
                                    <tr>
                                        <td>{{x.type}}</td>
                                        <td>Episódio {{x.number}} - Temporada {{x.season__number}} - <a class="detalhe" href="{% url 'series:ListSeasonSerie' x.season__serie__id %}">{{x.season__serie__or_title}}</a></td>
                                        <td>{{x.date_watched}}</td>
                                    </tr>
                                {% elif x.type == 'Anime' %}
                                    <tr>
                                        <td>{{x.type}}</td>
                                        <td>Episódio {{x.number}} - Temporada {{x.season__number}} - <a class="detalhe" href="{% url 'animes:ListSeasonAnime' x.season__anime__id %}">{{x.season__anime__or_title}}</a></td>
                                        <td>{{x.date_watched}}</td>
                                    </tr>
                                {% elif x.type == 'Mangá' %}
                                    <tr>
                                        <td>{{x.type}}</td>
                                        <td>Capítulo {{x.number}} - Volume {{x.volume__number}} - <a class="detalhe" href="{% url 'mangas:ListVolumeManga' x.volume__manga__id %}">{{x.volume__manga__or_title}}</a></td>
                                        <td>{{x.date_watched}}</td>
                                    </tr>
                               {%endif%}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endblock %} 
        </div>
    </div>
</article>
{%endblock%}