apps/animes/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListAnime, name='ListAnime'),
    path('<int:id>/', views.ListSeasonAnime, name='ListSeasonAnime'),
    path('<int:anime_id>/<int:season_id>/', views.ListEpisodeAnime, name='ListEpisodeAnime'),
    path('inserirepisodeanime/<int:episode_id>/', views.InserirAssistidoEpisodeAnime, name='InserirAssistidoEpisodeAnime'),
    path('inserirseasonanime/<int:season_id>/<int:anime_id>/', views.InserirAssistidoSeasonAnime, name='InserirAssistidoSeasonAnime'),
    path('inserirfavoritoanime/<int:anime_id>/', views.InserirAnimeFavorito, name='InserirAnimeFavorito'),
    path('adicionarNovoEP/<int:season_id>/<int:anime_id>/', views.AdicionarNovoEP, name='AdicionarNovoEP')
]

apps/books/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListBook, name='ListBook'),
    path('inserirlido/<int:book_id>/', views.InserirLido, name='InserirLido'),
]

apps/core/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

apps/mangas/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListManga, name='ListManga'),
    path('<int:id>/', views.ListVolumeManga, name='ListVolumeManga'),
    path('<int:manga_id>/<int:volume_id>/', views.ListChapterManga, name='ListChapterManga'),
    path('inserirchaptermanga/<int:chapter_id>/', views.InserirLidoChapterManga, name='InserirLidoChapterManga'),
    path('inserirvolumemanga/<int:volume_id>/<int:manga_id>/', views.InserirLidoVolumeManga, name='InserirLidoVolumeManga'),
]

apps/movies/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListMovie, name='ListMovie'),
    path('inserir_assistido/<int:filme_id>/', views.inserir_assistido, name='inserir_assistido'),
]

keepcontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views

urlpatterns = [ 
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('animes/', include(('apps.animes.urls', 'animes'), namespace='animes')),
    path('filmes/', include(('apps.movies.urls', 'movies'), namespace='movies')),    
    path('series/', include(('apps.series.urls', 'series'), namespace='series')),
    path('livros/', include(('apps.books.urls', 'books'), namespace='books')),    
    path('mangas/', include(('apps.mangas.urls', 'mangas'), namespace='mangas')), 
    path('conta/', include(('apps.accounts.urls','accounts'), namespace='accounts')) ,
    path('admin/', admin.site.urls)
]

keepcontrol/apps/core/models.py
from django.db import models

class Conteudo(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255)
    created_at = models.DateTimeField('Cadastrado em', auto_now_add=True)
    modified_at = models.DateField('Modificado em', auto_now=True)
    
    class Meta:
        abstract = True

apps/core/views.py
from django.shortcuts import render
from apps.animes.models import Anime
from apps.series.models import Serie
from apps.movies.models import Movie
from apps.books.models import Book
from apps.mangas.models import Manga
from itertools import chain
# Create your views here.

def home (request):
    context = {}
    animes = Anime.objects.all().order_by('-created_at')[:5]
    movies = Movie.objects.all().order_by('-created_at')[:5]
    series = Serie.objects.all().order_by('-created_at')[:5]
    books = Book.objects.all().order_by('-created_at')[:5]
    mangas = Manga.objects.all().order_by('-created_at')[:5]

    for x in animes:
        x.type = 'Anime'
    for x in series:
        x.type = 'Série'
    for x in movies:
        x.type = 'Filme'
    for x in books:
        x.type = 'Livro'
    for x in mangas:
        x.type = 'Mangá'
    
    todos = list(chain(animes,movies,series,books,mangas))
        
    todos_ordenados = sorted(todos, key=lambda x: x.created_at, reverse=True)
    
    template_name = 'home.html'
    context['all'] = todos_ordenados

    return render(request, template_name, context)

apps/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard.css'%}" />
    <link rel="stylesheet" href="{% static 'css/dashboard-double-sides.css'%}" />
    <link rel="stylesheet" href="{% static 'css/pagination_buttons.css'%}" />
    <link rel="stylesheet" href="{% static 'css/search-input.css'%}" />
    <link rel="stylesheet" href="{% static 'css/form-add.css'%}" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    
    <title>Keep Control</title>
    <link rel="icon" type="image/png" href="{% static 'images/painel-de-controle.png'%}">
    <style>

      
    </style>
</head>
<body>
  <nav> 
    <ul>
        <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}"><a href="{% url 'core:home' %}">Home</a></li>
        <li class="{% if request.resolver_match.url_name == 'ListSerie' %}active{% endif %}"><a href="{% url 'series:ListSerie' %}">Séries</a></li>
        <li class="{% if request.resolver_match.url_name == 'ListMovie' %}active{% endif %}"><a href="{% url 'movies:ListMovie' %}">Filmes</a></li>
        <li class="{% if request.resolver_match.url_name == 'ListAnime' %}active{% endif %}"><a href="{% url 'animes:ListAnime' %}">Animes</a></li>
        <li class="{% if request.resolver_match.url_name == 'ListBook' %}active{% endif %}"><a href="{% url 'books:ListBook' %}">Livros</a></li>
        <li class="{% if request.resolver_match.url_name == 'ListManga' %}active{% endif %}"><a href="{% url 'mangas:ListManga' %}">Mangás</a></li>
        {% if user.is_authenticated %} <!-- Se há algum usuário autenticado, -->
        <li class="{% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}"><a href="{%url 'accounts:dashboard'%}">Painel</a></li>
        <li><a href="{%url 'accounts:logout'%}">Sair</a></li>
        {% else %}
        <li><a href="{%url 'accounts:login'%}">Entrar</a></li>
        {% endif %}
      </ul>
  </nav>
  
  {% block principal %} {% endblock%}
 
  <footer>
    Todos os direitos reservados a &copy; Ewerson Pulquerio Santos, 2023
  </footer>
</body>
</html>

apps/core/templates/home.html
{% extends "base.html" %}

{% block principal %}

<article>
    <h3 style="text-align: center;">keepcontrol - O melhor site de controle de conteúdo assistido da internet!</h3>
    
    <h4>Últimos adicionados</h4>
    
    <table class='table_c'>
        {% for x in all %}
        <tr>
            
            {%if x.pt_title %}
                <td>
                    <a class="detalhe" href="{{ x.get_absolute_url }}">
                        {{x.pt_title}}
                    </a>
                </td>
            {%else%}
                <td>
                    <a class="detalhe" href="{{ x.get_absolute_url }}">
                        {{x.or_title}}
                    </a>
                </td>
            {%endif%}
            <td>
                {%if x.situation%}
                    {{x.situation}}
                {%else%}
                    {{x.year}}
                {%endif%}
            </td>
            <td>
                {{x.type}}
            </td>
        </tr>
        {% endfor %}
    </table>
</article>
{% endblock %}