apps/series/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListSerie, name='ListSerie'),
    path('<int:id>/', views.ListSeasonSerie, name='ListSeasonSerie'),
    path('<int:serie_id>/<int:season_id>/', views.ListEpisodeSerie, name='ListEpisodeSerie'),
    path('inserirepisodeanime/<int:episodeserie_id>/', views.InserirAssistidoEpisodeSerie, name='InserirAssistidoEpisodeSerie'),
    path('inserirseasonserie/<int:season_id>/<int:serie_id>/', views.InserirAssistidoSeasonSerie, name='InserirAssistidoSeasonSerie'),
    path('inserirfavoritaserie/<int:serie_id>/', views.InserirSerieFavorita, name='InserirSerieFavorita'),
    path('adicionarNovoEP/<int:season_id>/<int:serie_id>/', views.AdicionarNovoEP, name='AdicionarNovoEP')
]

keepcontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views

urlpatterns = [ 
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('animes/', include(('apps.animes.urls', 'animes'), namespace='animes')),
    path('filmes/', include(('apps.movies.urls', 'movies'), namespace='movies')),    
    path('series/', include(('apps.series.urls', 'series'), namespace='series')),
    path('livros/', include(('apps.books.urls', 'books'), namespace='books')),    
    path('mangas/', include(('apps.mangas.urls', 'mangas'), namespace='mangas')), 
    path('conta/', include(('apps.accounts.urls','accounts'), namespace='accounts')) ,
    path('admin/', admin.site.urls)
]

apps/series/models.py
from django.db import models


class Serie(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255)
    director = models.CharField('Diretor', null=True, max_length=255, blank=True)
    situation = models.CharField('Situação', null=True, blank=True)
    created_at = models.DateTimeField('Cadastrado em', auto_now_add=True)
    modified_at = models.DateField('Modificado em', auto_now=True)
    
    def __str__ (self):
        if self.pt_title:
            return self.pt_title
        else:
            return self.or_title
    
    def get_absolute_url(self):
        return '/series/'+ str(self.id) #retorna a URL do curso

    def insert_temps(self, qtd_temps):
            cont = 0
            for i in range(qtd_temps):
                number_of_season = i+1
            
                temp = SeasonSerie(number=number_of_season, serie_id=self.id)
                if SeasonSerie.objects.filter(number=temp.number, serie_id=temp.serie_id).exists():
                    print('Temporada '+str(number_of_season)+' já existe')
                    #Se a temporada existe, não fazer nada.
                else:
                    #Se a temporada não existe, inserir no banco.
                    temp.save()
                    print('Temporada '+str(temp.number)+' inserida!')
                    cont = cont+1
            return 'Número de temporadas adicionadas: '+str(cont)
        
    class Meta: 
        verbose_name = 'Série'
        verbose_name_plural = 'Séries'
        ordering = ['pt_title']

class SeasonSerie(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255, blank=True, null=True)
    number = models.BigIntegerField('Temporada')
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE, verbose_name="Série")

    def __str__ (self):
        if self.serie.pt_title:
            return f"{self.serie.pt_title} - Temporada {self.number}"
        else:
            return f"{self.serie.or_title} - Season {self.number}"
    
    def get_qtd_seasons(serie_id):
        return SeasonSerie.objects.filter(serie_id=serie_id).count() #Número de temporadas da série com este ID
        
    def get_seasons(serie_id):
        return SeasonSerie.objects.filter(serie_id=serie_id) #As temporaas da série com este ID
    
    def get_absolute_url(self):
        return '/series/'+ str(self.serie_id)+'/'+ str(self.id)
    
    def descricao_completa(self):
            return f"{self.__class__.__name__}: {', '.join([f'{chave}={valor}' for chave, valor in self.__dict__.items()])}"
    
    def insert_eps(self, qtd_eps):
        cont = 0
        for i in range(qtd_eps):
            number_of_ep = i+1
            title_of_episode_for_insert = 'Episódio '+str(number_of_ep) 
            id_of_season = self.id
            temp = EpisodeSerie(number=number_of_ep, season_id=id_of_season)
            if EpisodeSerie.objects.filter(number=temp.number, season_id=temp.season_id).exists():
                print(title_of_episode_for_insert+' já existe')
                #Se o episódio existir, não fazer nada.
            else:
                #Se o episódio não existir, inserir no banco.
                temp.save()
                print('EP: '+str(temp.number)+' inserido!')
                cont = cont+1
        return 'Número de episódios adicionados: '+str(cont)
    
    class Meta:
        verbose_name = 'Temporada'
        verbose_name_plural = 'Temporadas'
        unique_together = ['number', 'serie']
        ordering = ['serie__pt_title', 'number']
            
class EpisodeSerie(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255, blank=True, null=True)
    number = models.BigIntegerField('Episódio')
    season = models.ForeignKey(SeasonSerie, on_delete=models.CASCADE, verbose_name="Temporada")
    
    def __str__ (self):
        if self.season.pt_title:
            return f"Episódio {self.number} - {self.season.pt_title} - {self.season.serie}"
        else:
            return f"Episódio {self.number} - Temporada {self.season.number} - {self.season.serie}"
    
    def get_qtd_episodes(season_id):
        return EpisodeSerie.objects.filter(season_id=season_id).count()
    
    def get_episodes(self, season_id):
        return EpisodeSerie.objects.filter(season_id=season_id)
        
    class Meta:
        verbose_name = 'Episódio'
        verbose_name_plural = 'Episódios'
        unique_together = ['number', 'season']

apps/series/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Serie, SeasonSerie, EpisodeSerie
from apps.accounts.models import UserEpisodeSerie, FavoriteSerie
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q

def ListSerie (request):
    
    search_query = request.GET.get('search') #Link com o form-serch no html
    
    if search_query:
        series = Serie.objects.filter(
            Q(pt_title__icontains=search_query) |  # Busca por título em português (case-insensitive)
            Q(or_title__icontains=search_query)    # Busca por título em inglês (case-insensitive)
        ).order_by('or_title')
    else:
        series = Serie.objects.all().order_by('-created_at')    
    
    #FAVORITOS
    user_id = request.user.id
    if user_id:
        favoritos = FavoriteSerie.objects.filter(user_id=user_id)
    else:
        favoritos = []
    

    for serie in series:
        temp_count = SeasonSerie.get_qtd_seasons(serie.id)
        serie.qtd_temps = temp_count

        for temp in favoritos: #Verifica quais animes já estão favoritados
            if temp.serie_id == serie.id and temp.user_id == user_id:
                serie.favorite = True
        
    
    movies_paginator = Paginator(series, 20) #Filtra apenas 20 de todos os animes
    
    page_num = request.GET.get('page')
   
    page = movies_paginator.get_page(page_num)
    
    
    template_name = 'ListSerie.html'
    context = {
        'page' : page,
        'qtd_series' : series.count
    }
    
    return render(request, template_name, context)

def ListSeasonSerie (request, id):
    context = {}

    serie = get_object_or_404(Serie, id=id)
    serie.qtd_temps = SeasonSerie.get_qtd_seasons(id) #Incluindo quantidade de temporadas como atributo de serie
    serie.qtd_total_eps = 0

    seasons = SeasonSerie.objects.filter(serie_id=id).order_by('number')
    for season in seasons:
        season.qtd_assistido = 0
        season.qtd_eps = EpisodeSerie.get_qtd_episodes(season.id)
        serie.qtd_total_eps += season.qtd_eps
        if request.user.is_authenticated:
            epsisodes = EpisodeSerie.objects.filter(season=season.id)
            for ep in epsisodes:
                if ep in request.user.episodes_serie.all():
                    season.qtd_assistido += 1

    context['seasons'] = seasons
    context['serie'] = serie
    template_name = 'ListSeasonSerie.html'

    return render(request, template_name, context)

def ListEpisodeSerie (request, serie_id, season_id):
    context = {}
    
    season = SeasonSerie.objects.filter(id=season_id)
    serie = Serie.objects.filter(id=serie_id)
    eps = EpisodeSerie.objects.filter(season_id=season_id).order_by('number')
    
    usuario = request.user #Pegando o usuário logado
    
    for ep in eps:
        user_episode = ep.userepisodeserie_set.filter(user=usuario.id).first()
        if user_episode and user_episode.date_watched:
            ep.date_watched = user_episode.date_watched
    
    template_name = 'ListEpisodeSerie.html'
    
    # pegado last season of the serie
    number_season = SeasonSerie.objects.filter(id=season_id).first().number #Numero da season que clicou
    quantidade_de_seasons = SeasonSerie.objects.filter(serie_id=serie_id).count() #Quantidade de Seasons
    
    last_season = False

    if number_season == quantidade_de_seasons: #Se a última season adicionar for igual a quantidade de seasons TRUE
        last_season = True
 

    context = {
        'eps': eps,
        'season': season.first(),
        'serie': serie.first(),
        'last_season': last_season
    }

    return render(request, template_name, context)

@login_required
def InserirAssistidoEpisodeSerie(request, episodeserie_id):
    episodio_serie = EpisodeSerie.objects.filter(id=episodeserie_id).first()
    season_id = episodio_serie.season.id
    serie_id = episodio_serie.season.serie_id
    
    usuario = request.user
    episodeserie_user = UserEpisodeSerie.objects.filter(user=usuario.id, episode=episodeserie_id)
    if episodeserie_user:
        print (str(episodeserie_user)+" já foi assistido pelo usuário")
        return redirect('series:ListEpisodeSerie', serie_id=serie_id, season_id=season_id )
    else:
        episodeserie_user = UserEpisodeSerie(episode=episodio_serie, user=usuario, date_watched=timezone.now()) #Depois alterar o banco para inserir a data automaticamente
        episodeserie_user.save()
        print (str(episodio_serie)+" inserido!")
        return redirect('series:ListEpisodeSerie', serie_id=serie_id, season_id=season_id )
    
@login_required
def InserirAssistidoSeasonSerie(request, season_id, serie_id):
    episodes_serie = EpisodeSerie.objects.filter(season=season_id)
    
    for ep in episodes_serie:
        ep_id = ep.id
        print(ep_id)
        InserirAssistidoEpisodeSerie(request=request,episodeserie_id=ep_id)
        
    return redirect('series:ListSeasonSerie', id=serie_id)

@login_required
def InserirSerieFavorita(request, serie_id):
    #Insere a serie como favorito!
    
    usuario = request.user
    seriefavorita_user = FavoriteSerie.objects.filter(user=usuario.id, serie_id=serie_id)
        
    if seriefavorita_user:
        print (str(seriefavorita_user)+" já foi favoritada pelo usuário")
        return redirect('series:ListSerie')
    else:
        x = FavoriteSerie(user=usuario, serie_id=serie_id)
        x.save()
        print (str(x)+" favoritada!")
        return redirect('series:ListSerie')
    
@login_required
def AdicionarNovoEP(request, season_id, serie_id):
    #Pegar número do último episódio da temporada
    try:
        x = EpisodeSerie.objects.filter(season_id=season_id).order_by('number').last().number
    except:
        x = 0
    #Soma +1 ao número do episódio
    x = x+1

    #Cria um novo episódio para aquela temporada
    novo_ep = EpisodeSerie(number=x, season_id=season_id)
    #Salvar esse novo episódio
    novo_ep.save()
        
    return redirect('series:ListEpisodeSerie', serie_id=serie_id, season_id=season_id)

apps/series/templates/ListEpisodeSerie.html
{% extends "ListSeasonSerie.html" %}

{% block principal %}
<article>
    <h3>
        {% block title %}
            {{block.super}} - Temporada {{season.number}}
        {% endblock %}
    </h3>
    {%block infor%}
        {{block.super}}
    {%endblock%}
   
    <table class="table_c">
        <tr>
            <th>Episódios</th>
            <th>Assistido</th>      
        </tr>
        {% for ep in eps %}
        <tr>
            {% if ep.pt_title %}
            <td>Episódio {{ep.number}}: {{ep.pt_title}}</td>
            {% elif ep.or_title %}
            <td>Episódio {{ep.number}}: {{ep.or_title}}</td>
            {% else %}
            <td>Episódio {{ep.number}}</td>
            {% endif %}
                {% if ep in user.episodes_serie.all %}  
                    <td><b>Já assistido</b> - {{ep.date_watched|date:"d/m/Y"}} </td>
                {%else%}
                    <td>Não assistido - <a href="{% url 'series:InserirAssistidoEpisodeSerie' ep.id %}">Assistir</a></td>
                {%endif%}
        </tr>
        {% endfor %}
        {%if last_season %}
        <tr>
            <td>
                <a href="{% url 'series:AdicionarNovoEP' season.id season.serie_id %}"> Novo EP </a>
            </td>
            <td>

            </td> 
        </tr>
        {%endif%}
    </table>

</article>
{% endblock %}

apps/series/templates/ListSeasonSerie.html
{% extends "base.html" %}

{% block principal %}
<article>
    <h3>
        {% block title %}
            {{serie.or_title}}
        {% endblock %}
    </h3>
    {%block infor %}
        Status do série: <b>{{serie.situation}}</b> | Atualizado em: <b>{{serie.modified_at}}</b>
    {%endblock%}
    | Quantidade de episódios: <b>{{serie.qtd_total_eps}}</b>
    <table class="table_c">
        <tr>
            <th>Temporada</th>
            <th>Episódios</th>
        </tr>
        {% for season in seasons %}
        <tr>
            {%if season.pt_title%}
                <td><a class="detalhe" href="{{ season.get_absolute_url }}">Temporada {{season.number}}: {{season.pt_title}}</a></td>
            {%else%}
                <td><a class="detalhe" href="{{ season.get_absolute_url }}">Temporada {{season.number}}</a></td>
            {%endif%}
                <td>Assistido {{season.qtd_assistido}} de {{season.qtd_eps}}{%if season.qtd_assistido is season.qtd_eps%}{%else%} - <a href="{% url 'series:InserirAssistidoSeasonSerie' season.id season.serie_id %}">Marcar como assistido</a>{%endif%}</td>
        </tr>
        {% endfor %}
    </table>

  </article>
  {% endblock %}

apps/series/templates/ListSerie.html
{% extends "base.html" %}

{% block principal %}
<article>
    <h3>Lista de Séries</h3>
    <!-- Pesquisa -->
    <form method="GET" id="search-form">
        <input type="text" name="search" placeholder="Digite o título da série...">
        <button type="submit">Buscar</button>
    </form>
    <!-- Pesquisa -->
    {% if qtd_series %}
    <table class="table_c">
        <tr>
            <th>Título</th>
            <th>Temporadas</th>
            <th>Situação</th>
        </tr>
        {% for serie in page %}
        <tr>
            <td><a class="detalhe" href="{{ serie.get_absolute_url }}">{{serie.or_title}}</a></td>
            <td>{{serie.qtd_temps}}</td>
            <td>{{serie.situation}}</td>      
            {%if serie.favorite %}
            <td>Salvo</td>
            {%else%}
            <td><a href="{% url 'series:InserirSerieFavorita' serie.id %}">Favoritar</a></td>
            {%endif%}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p><b>Quantidade de séries cadastradas: {{qtd_series}}</b></p>
    {% endif %}
    <!-- Paginação -->
    <div class="pagination-div">
        <ul>
            {% if page.has_previous %}
                {% if page.previous_page_number > 1 %}
                    <li><a  href="{% url 'series:ListSerie'%}?page=1{% if search_query %}&search={{ search_query }}{% endif %}"><<</a></li> 
                {% endif %}
                <li title="{{page.previous_page_number}}"><a href="{% url 'series:ListSerie'%}?page={{page.previous_page_number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.previous_page_number }}</a></li>
            {% endif %}
            <li title="{{page.number}}" class="activated"><a href="{% url 'series:ListSerie'%}?page={{page.number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.number }}</a></li>
            {% if page.has_next %}
                <li title="{{page.next_page_number}}"><a href="{% url 'series:ListSerie'%}?page={{page.next_page_number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.next_page_number }}</a></li>
                {% if page.next_page_number < qtd_pages %}
                <li title="{{qtd_pages}}"><a href="{% url 'series:ListSerie'%}?page={{qtd_pages}}{% if search_query %}&search={{ search_query }}{% endif %}">>></a></li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
    <!-- Paginação -->

  </article>
  {% endblock %}