apps/animes/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.ListAnime, name='ListAnime'),
    path('<int:id>/', views.ListSeasonAnime, name='ListSeasonAnime'),
    path('<int:anime_id>/<int:season_id>/', views.ListEpisodeAnime, name='ListEpisodeAnime'),
    path('inserirepisodeanime/<int:episode_id>/', views.InserirAssistidoEpisodeAnime, name='InserirAssistidoEpisodeAnime'),
    path('inserirseasonanime/<int:season_id>/<int:anime_id>/', views.InserirAssistidoSeasonAnime, name='InserirAssistidoSeasonAnime'),
    path('inserirfavoritoanime/<int:anime_id>/', views.InserirAnimeFavorito, name='InserirAnimeFavorito'),
    path('adicionarNovoEP/<int:season_id>/<int:anime_id>/', views.AdicionarNovoEP, name='AdicionarNovoEP')
]

keepcontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.core import views

urlpatterns = [ 
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path('animes/', include(('apps.animes.urls', 'animes'), namespace='animes')),
    path('filmes/', include(('apps.movies.urls', 'movies'), namespace='movies')),    
    path('series/', include(('apps.series.urls', 'series'), namespace='series')),
    path('livros/', include(('apps.books.urls', 'books'), namespace='books')),    
    path('mangas/', include(('apps.mangas.urls', 'mangas'), namespace='mangas')), 
    path('conta/', include(('apps.accounts.urls','accounts'), namespace='accounts')) ,
    path('admin/', admin.site.urls)
]

apps/animes/models.py
from django.db import models

class Anime(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255)
    author = models.CharField('Autor', null=True, max_length=255, blank=True)
    situation = models.CharField('Situação', null=True, blank=True)
    created_at = models.DateTimeField('Cadastrado em', auto_now_add=True)
    modified_at = models.DateField('Modificado em', auto_now=True)
    
    def __str__ (self):
        if self.pt_title:
            return self.pt_title
        else:
            return self.or_title
    
    def get_absolute_url(self):
        return '/animes/'+ str(self.id) #retorna a URL do curso
        
    def insert_temps(self, qtd_temps):
            cont = 0
            for i in range(qtd_temps):
                number_of_season = i+1
                temp = SeasonAnime(number=number_of_season, anime_id=self.id)
                if SeasonAnime.objects.filter(number=number_of_season, anime_id=self.id).exists():
                    print('Temporada '+str(number_of_season)+' já existe')
                    #Se a temporada existe, não fazer nada.
                else:
                    #Se a temporada não existe, inserir no banco.
                    temp.save()
                    print('Temporada '+str(temp.number)+' inserida!')
                    cont = cont+1
            return 'Número de temporadas adicionadas: '+str(cont)
    
    def descricao_completa(self):
            return f"{self.__class__.__name__}: {', '.join([f'{chave}={valor}' for chave, valor in self.__dict__.items()])}"

    class Meta:
        verbose_name = 'Anime'
        verbose_name_plural = 'Animes'
        ordering = ['pt_title']

class SeasonAnime(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255, blank=True, null=True)
    number = models.BigIntegerField('Temporada')
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, verbose_name="Anime")
       
    def __str__ (self):
        return f"Temporada {self.number} - {self.anime.or_title}"
        # if self.anime.pt_title:
        #     return f"Temporada {self.number} - {self.anime.pt_title}"
        # else:
        #     return f"Temporada {self.number} - {self.anime.or_title}"
    
    def get_qtd_seasons(anime_id):
        return SeasonAnime.objects.filter(anime_id=anime_id).count() #Número de temporadas da série com este ID
        
    def get_seasons(anime_id):
        return SeasonAnime.objects.filter(anime_id=anime_id) #As temporaas da série com este ID
    
    def get_absolute_url(self):
        return '/animes/'+ str(self.anime_id)+'/'+ str(self.id)
    
    def insert_eps(self, qtd_eps, number_ep):
        cont = 0
        for i in range(qtd_eps):
            x = i+number_ep
            
            temp = EpisodeAnime(number=x, season_id=self.id)
            if EpisodeAnime.objects.filter(number=temp.number, season_id=temp.season_id).exists():
                print('Episódio '+str(x)+' já existe')
                #Se o episódio existir, não fazer nada.
            else:
                #Se o episódio não existir, inserir no banco.
                temp.save()
                print('Episódio '+str(temp.number)+' inserido!')
                cont = cont+1
            
        return 'Número de episódios adicionados: '+str(cont)
    
    class Meta:
        verbose_name = 'Temporada'
        verbose_name_plural = 'Temporadas'
        unique_together = ['number', 'anime']
        ordering = ['anime__or_title', 'number']
        
class EpisodeAnime(models.Model):
    pt_title = models.CharField('Título brasileiro', max_length=255, blank=True, null=True)
    or_title = models.CharField('Título original', max_length=255, blank=True, null=True)
    number = models.BigIntegerField('Episódio')
    season = models.ForeignKey(SeasonAnime, on_delete=models.CASCADE, verbose_name="Temporada")
    
    def __str__ (self):
        if self.season.pt_title:
            return f"Episódio {self.number} - Saga {self.season.pt_title} - {self.season.anime}"
        else:
            return f"Episódio {self.number} - Temporada {self.season.number} - {self.season.anime}"
    
    def get_qtd_episodes(id):
        return EpisodeAnime.objects.filter(season_id=id).count()
    
    def get_episodes(self, id_da_season):
        return EpisodeAnime.objects.filter(season_id=id_da_season)
    
    # def insert_eps(self, qtd_eps, season_id):
    #     cont = 0
    #     for i in range(qtd_eps):
    #         number_of_ep = i+1
    #         title_of_episode_for_insert = 'Episódio '+str(number_of_ep) 
    #         temp = EpisodeAnime(number=number_of_ep, season_id=season_id)
    #         if EpisodeAnime.objects.filter(number=temp.number, season_id=temp.season_id).exists():
    #             print(title_of_episode_for_insert+' já existe')
    #             #Se o episódio existir, não fazer nada.
    #         else:
    #             #Se o episódio não existir, inserir no banco.
    #             temp.save()
    #             print('EP: '+str(temp.number)+' inserido!')
    #             cont = cont+1
    #     return 'Número de episódios adicionados: '+str(cont)
    
    class Meta:
        verbose_name = 'Episódio'
        verbose_name_plural = 'Episódios'

apps/animes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Anime, SeasonAnime, EpisodeAnime
from apps.accounts.models import UserEpisodeAnime, FavoriteAnime
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from django.db.models import Q

def ListAnime (request):
    
    search_query = request.GET.get('search') #Link com o form-serch no html
    
    if search_query:
        animes = Anime.objects.filter(
            Q(pt_title__icontains=search_query) |  # Busca por título em português (case-insensitive)
            Q(or_title__icontains=search_query)    # Busca por título em inglês (case-insensitive)
        ).order_by('or_title')
    else:
        animes = Anime.objects.all().order_by('-created_at')    
    
    user_id = request.user.id
    if user_id:
        favoritos = FavoriteAnime.objects.filter(user_id=user_id)
    else:
        favoritos = []
    
    for anime in animes:
        temp_count = SeasonAnime.get_qtd_seasons(anime.id)
        anime.qtd_temps = temp_count
        
        anime.descricao_completa()
                
        for temp in favoritos: #Verifica quais animes já estão favoritados
            if temp.anime_id == anime.id and temp.user_id == user_id:
                anime.favorite = True
        
    movies_paginator = Paginator(animes, 20) #Filtra apenas 20 de todos os animes
    
    page_num = request.GET.get('page')
   
    page = movies_paginator.get_page(page_num)
    
    template_name = 'ListAnime.html'
    context = {
        'page': page,
        'qtd_animes' : animes.count,
        'qtd_pages': movies_paginator.num_pages,
        'search_query': search_query  # Passar o valor de busca para o template
    }

    return render(request, template_name, context)

def ListSeasonAnime (request, id):
    context = {}

    anime = get_object_or_404(Anime, id=id)
    anime.qtd_temps = SeasonAnime.get_qtd_seasons(id) #Incluindo quantidade de temporadas como atributo de anime
    anime.qtd_total_eps = 0

    seasons = SeasonAnime.objects.filter(anime_id=id).order_by('number')
        
    for season in seasons:
        season.qtd_assistido = 0
        season.qtd_eps = EpisodeAnime.get_qtd_episodes(season.id)
        anime.qtd_total_eps += season.qtd_eps
        if request.user.is_authenticated:
            epsisodes = EpisodeAnime.objects.filter(season=season.id)
            for ep in epsisodes:
                if ep in request.user.episodes_anime.all():
                    season.qtd_assistido += 1
    
    template_name = 'ListSeasonAnime.html'
    
    context = {
        'seasons': seasons,
        'anime': anime,
        
    }    

    return render(request, template_name, context)

def ListEpisodeAnime (request, anime_id, season_id):
    context = {}
    
    season = SeasonAnime.objects.filter(id=season_id)
    anime = Anime.objects.filter(id=anime_id)
    eps = EpisodeAnime.objects.filter(season_id=season_id).order_by('number')
    
    usuario = request.user #Pegando o usuário logado
    
    for ep in eps:
        user_episode = ep.userepisodeanime_set.filter(user=usuario.id).first()
        if user_episode and user_episode.date_watched:
            ep.date_watched = user_episode.date_watched
    
    # pegado last season of the anime
    number_season = SeasonAnime.objects.filter(id=season_id).first().number #Numero da season que clicou
    quantidade_de_seasons = SeasonAnime.objects.filter(anime_id=anime_id).count() #Quantidade de Seasons
    
    last_season = False

    if number_season == quantidade_de_seasons: #Se a última season adicionar for igual a quantidade de seasons TRUE
        last_season = True

    context['last_season'] = last_season
    context['eps'] = eps
    context['season'] = season.first()
    context['anime'] = anime.first()
    template_name = 'ListEpisodeAnime.html'
    
    return render(request, template_name, context)

@login_required
def InserirAssistidoEpisodeAnime(request, episode_id):
    #Insere um episódio do anime como assistido pelo usuário logado!
    episodio_anime = EpisodeAnime.objects.filter(id=episode_id).first()
    season_id = episodio_anime.season.id
    anime_id = episodio_anime.season.anime_id
    
    if (False):
        date = '2021-01-14 00:00:00'
    else:
        date = timezone.now()

    usuario = request.user
    episodeanime_user = UserEpisodeAnime.objects.filter(user=usuario.id, episode=episode_id)
        
    if episodeanime_user:
        #print (str(episodeanime_user)+" já foi assistido pelo usuário")
        return redirect('animes:ListEpisodeAnime', anime_id=anime_id, season_id=season_id)
    else:
        x = UserEpisodeAnime(episode=episodio_anime, user=usuario, date_watched=date) #timezone.now()Depois alterar o banco para inserir a data automaticamente
        x.save()
        #print (str(episodio_anime)+" inserido!")
        return redirect('animes:ListEpisodeAnime', anime_id=anime_id, season_id=season_id)

@login_required
def InserirAssistidoSeasonAnime(request, season_id, anime_id):
    #Insere todos os episódios de uma temporada de um anime como assistidos pelo usuário logado!
    episodes_anime = EpisodeAnime.objects.filter(season=season_id)
    
    for ep in episodes_anime:
        x = ep.id
        print(x)
        InserirAssistidoEpisodeAnime(request=request,episode_id=x)
        
    return redirect('animes:ListSeasonAnime', id=anime_id)

@login_required
def InserirAnimeFavorito(request, anime_id):
    #Insere o anime como favorito!
    
    usuario = request.user
    animefavorito_user = FavoriteAnime.objects.filter(user=usuario.id, anime_id=anime_id)
        
    if animefavorito_user:
        print (str(animefavorito_user)+" já foi favoritado pelo usuário")
        return redirect('animes:ListAnime')
    else:
        x = FavoriteAnime(user=usuario, anime_id=anime_id)
        x.save()
        print (str(x)+" favoritado!")
        return redirect('animes:ListAnime')

@login_required
def AdicionarNovoEP(request, season_id, anime_id):
    
    #Pegar número do último episódio da temporada e não tiver último zera

    try:
        x = EpisodeAnime.objects.filter(season_id=season_id).order_by('number').last().number
    except:
        x = 0
    
    #Soma +1 ao número do episódio
    x = x+1
    #Cria um novo episódio para aquela temporada
    novo_ep = EpisodeAnime(number=x, season_id=season_id)
    #Salvar esse novo episódio
    novo_ep.save()
        
    return redirect('animes:ListEpisodeAnime', anime_id=anime_id, season_id=season_id)

apps/animes/templates/ListAnime.html
{% extends "base.html" %}

{% block principal %}
<article>
    <h3>Lista de Animes</h3>
     <!-- Pesquisa -->
     <form method="GET" id="search-form">
        <input type="text" name="search" placeholder="Digite o título do anime...">
        <button type="submit">Buscar</button>
    </form>
    <!-- Pesquisa -->
    {% if qtd_animes %}
    <table class="table_c">
        <tr>
            <th>Título</th>
            <th>Temporadas</th>
            <th>Situação</th>
            <th>#</th>
        </tr>
        {% for anime in page %}
        <tr>
            <td><a class="detalhe" href="{{ anime.get_absolute_url }}">{{anime.or_title}}</a></td>
            <td>{{anime.qtd_temps}}</td>
            <td>{{anime.situation}}</td>
            {%if anime.favorite %}
            <td>Salvo</td>
            {%else%}
            <td><a href="{% url 'animes:InserirAnimeFavorito' anime.id %}">Favoritar</a></td>
            {%endif%}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p><b>Quantidade de animes cadastrados: {{qtd_animes}}</b></p>
    {% endif %}

    <div class="pagination-div">
        <ul>
            {% if page.has_previous %}
                {% if page.previous_page_number > 1 %}
                    <li title="{{1}}"><a href="{% url 'animes:ListAnime'%}?page=1{% if search_query %}&search={{ search_query }}{% endif %}"><<</a></li> 
                {% endif %}
                <li title="{{page.previous_page_number}}"><a href="{% url 'animes:ListAnime'%}?page={{page.previous_page_number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.previous_page_number }}</a></li>
            {% endif %}
            <li title="{{page.number}}" class="activated"><a href="{% url 'animes:ListAnime'%}?page={{page.number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.number }}</a></li>
            {% if page.has_next %}
                <li title="{{page.next_page_number}}"><a href="{% url 'animes:ListAnime'%}?page={{page.next_page_number}}{% if search_query %}&search={{ search_query }}{% endif %}">{{ page.next_page_number }}</a></li>
                {% if page.next_page_number < qtd_pages %}
                <li title="{{qtd_pages}}"><a href="{% url 'animes:ListAnime'%}?page={{qtd_pages}}{% if search_query %}&search={{ search_query }}{% endif %}">>></a></li>
                {% endif %}
            {% endif %}
        </ul>
    </div>

  </article>
  {% endblock %}

apps/animes/templates/ListEpisodeAnime.html
{% extends "ListSeasonAnime.html" %}

{% block principal %}
<article>
    <h3>
        {% block title %}
            {{block.super}} - Temporada {{season.number}}{%if season.pt_title%}: {{season.pt_title}}{%endif%}
        {% endblock %}
    </h3>
    {%block infor%}
        {{block.super}}
    {%endblock%}
   
    <table class="table_c">
        <tr>
            <th>Episódios</th>
            <th>Assistido</th>      
        </tr>
        {% for ep in eps %}
        <tr>
            {% if ep.pt_title %}
            <td>Episódio {{ep.number}}: {{ep.pt_title}}</td>
            {% else %}
            <td>Episódio {{ep.number}}</td>
            {% endif %}
                {% if ep in user.episodes_anime.all %}  
                    <td><b>Já assistido</b> - {{ep.date_watched|date:"d/m/Y"}} </td>
                {%else%}
                <td>Não assistido - <a href="{% url 'animes:InserirAssistidoEpisodeAnime' ep.id %}">Assistir</a></td>
                {%endif%}
        </tr>
        {% endfor %}
        {%if last_season %}
        <tr>
            <td>
                <a href="{% url 'animes:AdicionarNovoEP' season.id season.anime_id %}"> Novo EP </a>
            </td>
            <td>

            </td> 
        </tr>
        {%endif%}

    </table>

  </article>
  {% endblock %}

apps/animes/templates/ListSeasonAnime.html
{% extends "base.html" %}

{% block principal %}
<article>
    <h3>
        {% block title %}
            {{anime.or_title}}
        {% endblock %}
    </h3>
    {%block infor %}
        Status do anime: <b>{{anime.situation}}</b> | Atualizado em: <b>{{anime.modified_at}}</b>
    {%endblock%}
    | Quantidade de episódios: <b>{{anime.qtd_total_eps}}</b>
    <table class="table_c">
        <tr>
            <th>Temporada</th>
            <th>Episódios</th>
        </tr>
        {% for season in seasons %}
        <tr>
            {%if season.pt_title%}
            <td><a class="detalhe" href="{{ season.get_absolute_url }}">Temporada {{season.number}}: {{season.pt_title}}</a></td>
            {%else%}
            <td><a class="detalhe" href="{{ season.get_absolute_url }}">Temporada {{season.number}}</a></td>
            {%endif%}
            <td>Assistido {{season.qtd_assistido}} de {{season.qtd_eps}}{%if season.qtd_assistido is season.qtd_eps%}{%else%} - <a href="{% url 'animes:InserirAssistidoSeasonAnime' season.id season.anime_id %}">Marcar como assistido</a>{%endif%}</td>   
        </tr>
        {% endfor %}
    </table>

  </article>
  {% endblock %}